### Goal Description

This goal aims to assess the amount of protection provided by marine and coastal habitats against flooding and erosion to coastal areas that people value, both inhabited (homes and other structures) and uninhabited (parks, special places, etc.). A score of 100 would indicate that these habitats are all still intact or have been restored to their reference conditions.

### Model & Data 

The CP model is based on the relative health of the habitats that provide shoreline protection, weighted by their area and protectiveness rank (Halpern 2015 final). Condition of each habitat was calculated with various methods depending on data availability, which are mostly based on coverage area. Rank weights for the protective ability of each habitat (Rk) come from previous work48 that ranks mangroves, corals and sea ice as 4, salt marshes as 3, and seagrasses as 1 (higher values are better) (Halpern 2012). 

Below are the data sets for this goal.

### Reference points 

A temporal reference point (ie. coverage data of a historical point) was used for each type of habitat. We generally considered the reference years to be between 1980-1995, although these varied by habitat due to data availability. 






