### Goal Description

The Carbon Storage goal captures the ability of the coastal habitats to remove carbon given their carbon uptake rate and health conditions. A score of 100 means all habitats that contribute to carbon removal are still intact or have been restored and they can function to their full carbon burial potential. Highly productive coastal wetland ecosystems or seagrass store substantially large amount of carbon have the highest sequestration rates of any habitats on earth. They are also threatened by under-regulated coastal development but are amenable to restoration and conservation efforts. 

### Model

Goal model measures the current ‘condition’ of habitats relative to reference conditions, weighted by the relative contribution of each habitat type to total carbon sequestration, using data from (Laffoley & Grimsditch 2009) (Halpern 2015 final). 

Three coastal habitats known to provide meaningful amounts of carbon storage were included in this goal: mangroves, seagrasses, and salt marshes (Halpern 2012). Habitat conditions are measured mainly by their coverage area, and their relative carbon sequestration are weighted: Mangrove as 139, Saltmarsh as	210, and Seagrass	as 83 (Halpern 2015 final). 


### Reference points 

A temporal reference point (ie. coverage data of a historical point) was used for each type of habitat. We generally considered the reference years to be between 1980-1995, although these varied by habitat due to data availability. 





