### Goal Description

People value marine waters that are free of pollution and debris for aesthetic and health reasons. Contamination of waters comes from oil spills, chemicals, eutrophication, algal blooms, disease pathogens (e.g., fecal coliform, viruses, and parasites from sewage outflow), floating trash, and mass kills of organisms due to pollution. People are sensitive to these phenomena occurring in areas that they access for recreation or other purposes as well as for simply knowing that clean waters exist. The Clean Water goal captures the degree to which local waters are unpolluted by natural and human-made causes. This goal scores highest when the contamination level is zero.

### Model

CW goal score is calculated as the geometric mean of its four components: eutrophication (nutrients), chemicals, pathogens and marine debris. They are meant to represent a comprohensive list of contamination categories that are commonly considered in assessments of coastal clean waters and for which we could obtain datasets. _Chemical pollution_ was measured as the average of land-based organic and inorganic pollution from agricultural pesticide use and runoff from impervious surfaces, respectively, and ocean-based pollution from commercial shipping and ports. The modeled input of land-based nitrogen input from (Halpern et al. 2008) was used as a proxy for _nutrient_ input. Due to a lack of information on direct measurements of human pathogen in the coastal water, we used a proxy measure for pathogen: the number of people in coastal areas without access to improved sanitation facilities, assuming that locations with fewer people with access to improved facilities would lead to a a higher likelihood of coastal water contamination from human pathogens. The status of _trash pollution_ was estimated using globally-available coastal beach cleanup data from the Ocean Conservancy, which records the weight of trash per year that were collected (Halpern 2012). 

### Reference points 

The reference point is when the contamination level is zero for all components.






