### Goal Description

The Fisheries sub-goal describes the amount of wild-caught seafood harvested and its sustainability for human consumption. The model generally compares landings with Maximum Sustainable Yield. A score of 100 means the country or region is harvesting seafood to the ecosystem’s production potential in an sustainable manner.

### Model 

The model assess the amount of wild-caught seafood that can be sustainably harvested, with sustainability based on multi-species yield, and with penalties assigned for both over- and under-harvesting. Each taxa landed within each FAO major fishing area is assessed separately based on B/BMSY (maxium sustainable yield) and weighted by its relative contribution to overall catch. The goal status score for each reporting region in each year was calculated as the geometric mean of the all stock status scores (Halpern 2015). 

<!-- _NOTE: mention model limitations here since FIS is such a difficult model and has many caveats?_
The model is based on single-species assessments of stock status and thus cannot predict the effect of multi-species interactions. -->

### Reference points

The reference point is B/BMSY, at which harvest is both maximal and sustainable. The estimates of B/BMSY were obtained by applying a model developed by Martell & Froese (2012), and hereafter referred to as the “catch-MSY” method. The latter was chosen, among other data-limited methods available, based on simulation-testing showing that it most accurately predicted stock status for simulated stocks having a broad range of life history traits and different known sources of uncertainty. The catch-MSY approach improves upon the method used in the 2012 OHI-Global assessment in that it: 1) leverages a mechanistic understanding of the connection between harvest dynamics and population dynamics and uses this to infer stock depletion levels (see also Thorson et al., 2013), 2) is an indicator of stock abundance (B) rather than catch, making it more directly informative of stock status, and 3) at least in some cases (i.e., those cases where the catch trajectory is not a monotonic increase), can be applied to developing fisheries (whereas the previous approach assumed a perfect score in those cases). 



